<a href="https://colab.research.google.com/github/pearl24680/python-practice/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
print (type(a))

<class 'numpy.ndarray'>


In [3]:
l = []
for i in range(1,8):
    j = int(input("enter a no. :"))
    l.append(j)


enter a no. :10
enter a no. :20
enter a no. :3
enter a no. :45
enter a no. :354
enter a no. :34
enter a no. :34


In [4]:
print(l)

[10, 20, 3, 45, 354, 34, 34]


In [5]:
print(type(l))

<class 'list'>


In [6]:
b = np.array(l)
print(b)

[ 10  20   3  45 354  34  34]


In [7]:
print(type(b))

<class 'numpy.ndarray'>


dimension we check from brackets

In [8]:
print(b.ndim)

1


create 2d array

In [9]:
c = [[10,20,30],[40,50,60]]
print(c)

[[10, 20, 30], [40, 50, 60]]


In [10]:
d = np.array(c)

In [11]:
print(d)

[[10 20 30]
 [40 50 60]]


In [12]:
print(d.ndim)

2


In [13]:
oa = np.ones(8)
print(oa)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
em = np.empty(9)
print(em)

[4.76026186e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000]


In [19]:
r = np.arange(2)
print(r)

[0 1]


In [21]:
i = np.identity(3) #eye or identity same
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
ar = np.linspace(10,20,num=15)
print(ar)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]


In [25]:
rn = np.random.rand(2,15)
print(rn)

[[0.40452063 0.34188573 0.75444154 0.99793705 0.79227068 0.77978084
  0.31561569 0.82096831 0.44305765 0.29977125 0.13327785 0.90912604
  0.10929171 0.00887223 0.70527678]
 [0.6712515  0.08011032 0.25142761 0.89307933 0.33997768 0.50469332
  0.93840562 0.06060073 0.51028066 0.86293833 0.9175205  0.76608841
  0.88431189 0.81213386 0.96662858]]


In [26]:
rn = np.random.randn(2,15)
print(rn)

[[-0.42968144  0.70965886  0.59147638 -0.88588236 -1.14049016 -0.19589922
  -0.90155872  1.23718088  1.44606777 -0.61897176  2.27410215  0.54166847
   0.27090779  0.94999501 -0.37553892]
 [ 1.57069365  0.40003095 -1.0496397  -0.15498507 -1.88576588  0.32183678
  -0.81895515 -0.83859565  0.93869446 -1.62038508  0.37419121 -0.88394158
   0.29392345  1.8308425  -0.3621263 ]]


In [28]:
rf = np.random.ranf(4)
print(rf)

[0.68298312 0.34819293 0.83854808 0.73616904]


In [29]:
ri = np.random.randint(10)
print(ri)

9


In [30]:
var = np.array([10,20,30,40,50,60])
print(var)

[10 20 30 40 50 60]


In [31]:
print(var.dtype)

int64


In [32]:
a = np.array([10,20,30,40,50,60],dtype=np.int8)
print(a)

[10 20 30 40 50 60]


In [33]:
print(type(a))

<class 'numpy.ndarray'>


In [34]:
var1 = np.array(["a","b","c"])
print(var1.dtype)

<U1


In [38]:
x = np.array(var, dtype="f")
print(x)

[10. 20. 30. 40. 50. 60.]


In [39]:
print(type(x))

<class 'numpy.ndarray'>


In [40]:
nw =np.float64(var)
print(nw.dtype)

float64


In [41]:
nn =np.float32(var)
print(nn.dtype)

float32


In [44]:
import numpy as np
v=np.array([[[[]]]])
print(v.ndim)

4


In [45]:
print(v.shape)

(1, 1, 1, 0)
